apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
    # colocando porta 30000 no cluster tipo NodePort , fixa esta porta para utilizarmos nos n처s. Todos os pods ser찾o acessados a partir do 
    # IP do n처 com a porta 30000;  (IP do n처 = kubectl get nodes -o wide)
  type: NodePort


  # docker container run --rm kubedevio/ubuntu-curl curl http://172.18.0.2:30379/temperatura/fahrenheitparacelsius/100

  # docker container run --rm kubedevio/ubuntu-curl curl http://172.18.0.2:30000/temperatura/fahrenheitparacelsius/100

   #curl http://172.18.0.2:30379/temperatura/fahrenheitparacelsius/100
