apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  # pod definition
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 27017
        envFrom:
        - configMapRef:
              name: mongodb-configmap 



# https://gist.github.com/troyharvey/4506472732157221e04c6b15e3b3f094

