apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP


#curl http://api-service/temperatura/fahrenheitparacelsius/100

#kubectl scale deployment api --replicas 30
